[font]
size = 18

[window]
opacity = 0.8  # Adjust this value (0.0 to 1.0) for more/less transparency
blur = true    # This requests blur from your compositor

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

import = [
    "~/.config/alacritty/tokyonight.toml"
]