[font]
size = 18

[window]
opacity = 0.8  # Adjust this value (0.0 to 1.0) for more/less transparency
blur = true    # This requests blur from your compositor

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[colors.primary]

background = '#1a1b26'
foreground = '#c0caf5'

[colors.cursor]

cursor = '#c0caf5'
text = '#1a1b26'

[colors.normal]

black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

[colors.bright]

black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

[[colors.indexed_colors]]

index = 16
color = '#ff9e64'

[[colors.indexed_colors]]

index = 17
color = '#db4b4b'